name: Dustin Who
favicon: null
layout_spectrum: 0.6965049901045859
typography_spectrum: 0.05618116585537791
title: 'Dustin Who!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19170c'
    - '#a1733d'
    - '#fbfcf6'
    - '#cfa94e'
    - '#cad949'
  brandStrength: 0.8934981257189065
  lightness: 0.7060027536936104
  saturation: 0.31136961840093136
  rhythmicContrast: 0.9355371729470789
purpose: []
